
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 28 11:26:42 ART 2020
//----------------------------------------------------

package Modelo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 13;
  public static final int Llave_c = 25;
  public static final int Llave_a = 24;
  public static final int MayI = 34;
  public static final int Update = 6;
  public static final int Delete = 7;
  public static final int From = 5;
  public static final int Set = 36;
  public static final int Into = 3;
  public static final int Menor = 32;
  public static final int MenI = 33;
  public static final int Select = 4;
  public static final int Mayor = 31;
  public static final int Punto = 11;
  public static final int Division = 21;
  public static final int Parentesis_c = 23;
  public static final int Values = 14;
  public static final int Parentesis_a = 22;
  public static final int EOF = 0;
  public static final int P_coma = 26;
  public static final int And = 12;
  public static final int error = 1;
  public static final int Distinto = 35;
  public static final int Show = 8;
  public static final int Use = 10;
  public static final int Linea = 16;
  public static final int ERROR = 29;
  public static final int Insert = 2;
  public static final int Create = 9;
  public static final int ComSimp = 30;
  public static final int Identificador = 27;
  public static final int Resta = 19;
  public static final int Multiplicacion = 20;
  public static final int Where = 15;
  public static final int Numero = 28;
  public static final int Suma = 18;
  public static final int Igual = 17;
}

